#!/bin/bash

################################################################################
# OPERATION KERNEL SHADOWS
# Episode 04: Package Management
# Script: install_report_generator.sh (Type B Solution)
#
# Mission: Generate installation report (MINIMAL VERSION)
# Author: Max Sokolov
# Date: 7 октября 2025
#
# Description:
#   Type B episode: 95% apt/dpkg, 5% bash
#   Это НЕ wrapper для apt! Только генератор отчёта.
#   Для установки пакетов используй apt напрямую!
################################################################################

set -euo pipefail

# === CONFIGURATION ===

TOOLS_FILE="${1:-../artifacts/required_tools.txt}"
REPORT_FILE="install_report.txt"

# === MAIN REPORT GENERATION ===

{
  echo "═══════════════════════════════════════════════════════════════"
  echo "           PACKAGE INSTALLATION REPORT"
  echo "═══════════════════════════════════════════════════════════════"
  echo ""
  echo "Date: $(date '+%d %B %Y, %H:%M')"
  echo "System: $(lsb_release -ds)"
  echo "Kernel: $(uname -r)"
  echo "Architecture: $(dpkg --print-architecture)"
  echo ""
  echo "───────────────────────────────────────────────────────────────"
  echo "INSTALLED PACKAGES FROM required_tools.txt"
  echo "───────────────────────────────────────────────────────────────"
  echo ""

  # Process each package
  while read -r pkg; do
    # Skip comments and empty lines
    [[ "$pkg" =~ ^#.*$ || -z "$pkg" ]] && continue

    # Check if installed
    if dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
      version=$(dpkg -l "$pkg" | grep "^ii" | awk '{print $3}')
      repo=$(apt-cache policy "$pkg" | grep -A 1 "Installed:" | tail -1 | awk '{print $2}' | sed 's|https://||; s|http://||')
      echo "  ✓ $pkg"
      echo "    Version: $version"
      echo "    Repository: $repo"
      echo ""
    else
      echo "  ✗ $pkg — NOT INSTALLED"
      echo ""
    fi
  done < "$TOOLS_FILE"

  echo "───────────────────────────────────────────────────────────────"
  echo "STATISTICS"
  echo "───────────────────────────────────────────────────────────────"
  echo ""

  # Total packages in system
  total_system=$(dpkg -l | grep "^ii" | wc -l)
  echo "Total packages in system: $total_system"

  # Packages from required list
  installed_count=0
  while read -r pkg; do
    [[ "$pkg" =~ ^# || -z "$pkg" ]] && continue
    if dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
      ((installed_count++))
    fi
  done < "$TOOLS_FILE"

  required_count=$(grep -v "^#" "$TOOLS_FILE" | grep -v "^$" | wc -l)
  echo "Packages from required list: $installed_count / $required_count"

  # Disk usage
  cache_size=$(du -sh /var/cache/apt/archives/ 2>/dev/null | awk '{print $1}' || echo "N/A")
  echo "Disk usage (apt cache): $cache_size"
  echo ""

  echo "═══════════════════════════════════════════════════════════════"
  echo "                      END OF REPORT"
  echo "═══════════════════════════════════════════════════════════════"
  echo ""
  echo "Generated by: Max Sokolov"
  echo "For: Viktor Petrov (OPERATION KERNEL SHADOWS)"

} > "$REPORT_FILE"

echo "✓ Report saved: $REPORT_FILE"
echo ""
echo "Preview:"
echo "───────────────────────────────────────────────────────────────"
cat "$REPORT_FILE"

