---
# KERNEL SHADOWS: Episode 16 — Common Role Handlers
# Service restart handlers
# Amsterdam → Berlin (Day 31-32)

################################################################################
# Handlers (triggered by notify:)
################################################################################

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded

################################################################################
# Klaus's Handler Philosophy:
#
# "Handlers run ONCE at the end of play, even if notified multiple times.
#  That's idempotency. That's efficiency.
#
#  Don't restart services in tasks → use notify + handlers
#  Ansible batches changes, minimizes downtime."
################################################################################


