# KERNEL SHADOWS: Episode 15 — GitHub Actions (Test)
# Continuous Integration Pipeline
# Berlin, Germany (Day 29-30)

name: CI - Test

on:
  push:
    branches: ['**']  # All branches
  pull_request:
    branches: [main, development]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning

      - name: Lint summary
        run: echo "✓ Lint passed"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bash curl jq

      - name: Run unit tests
        run: |
          chmod +x tests/run_tests.sh
          ./tests/run_tests.sh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/results.xml
          retention-days: 7

      - name: Test summary
        run: echo "✓ Tests passed"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Security summary
        run: echo "✓ Security scan completed"

  report:
    name: Test Report
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    if: always()

    steps:
      - name: Test summary
        run: |
          echo "========================================="
          echo "CI REPORT"
          echo "========================================="
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Author: ${{ github.actor }}"
          echo "Workflow: ${{ github.run_number }}"
          echo "========================================="


