---
# KERNEL SHADOWS: Episode 16 — Common Role
# Tasks applied to ALL servers
# Amsterdam → Berlin (Day 31-32)

################################################################################
# System Updates & Package Management
################################################################################

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Upgrade all packages to latest
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  when: allow_system_upgrade | default(false)
  tags:
    - packages
    - upgrade

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
  tags:
    - packages

################################################################################
# Timezone & NTP
################################################################################

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags:
    - timezone

- name: Install and configure NTP
  apt:
    name: ntp
    state: present
  tags:
    - ntp

- name: Configure NTP servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart ntp
  tags:
    - ntp

################################################################################
# User Management
################################################################################

- name: Create system users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups | join(',') }}"
    shell: "{{ item.shell }}"
    create_home: yes
    state: present
  loop: "{{ system_users }}"
  tags:
    - users

- name: Deploy SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  loop: "{{ system_users }}"
  when: item.ssh_key is defined
  tags:
    - users
    - ssh

################################################################################
# SSH Hardening
################################################################################

- name: Configure SSH server
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart sshd
  tags:
    - ssh
    - security

- name: Disable root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart sshd
  tags:
    - ssh
    - security

################################################################################
# Firewall (UFW)
################################################################################

- name: Install UFW
  apt:
    name: ufw
    state: present
  tags:
    - firewall

- name: Configure UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  tags:
    - firewall

- name: Allow SSH through firewall
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  tags:
    - firewall

- name: Allow other ports through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ firewall_allowed_ports }}"
  tags:
    - firewall

- name: Enable UFW
  ufw:
    state: enabled
  tags:
    - firewall

################################################################################
# Fail2ban (Brute Force Protection)
################################################################################

- name: Install Fail2ban
  apt:
    name: fail2ban
    state: present
  when: fail2ban_enabled
  tags:
    - security
    - fail2ban

- name: Configure Fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  when: fail2ban_enabled
  notify: restart fail2ban
  tags:
    - security
    - fail2ban

################################################################################
# Monitoring (Node Exporter)
################################################################################

- name: Install Node Exporter for Prometheus
  apt:
    name: prometheus-node-exporter
    state: present
  when: node_exporter_enabled
  tags:
    - monitoring

- name: Ensure Node Exporter is running
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
  when: node_exporter_enabled
  tags:
    - monitoring

################################################################################
# System Tuning
################################################################################

- name: Apply sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ sysctl_settings | dict2items }}"
  when: sysctl_settings is defined
  tags:
    - tuning

- name: Set system limits
  pam_limits:
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - { limit_type: 'soft', limit_item: 'nofile', value: "{{ max_open_files }}" }
    - { limit_type: 'hard', limit_item: 'nofile', value: "{{ max_open_files }}" }
    - { limit_type: 'soft', limit_item: 'nproc', value: "{{ max_processes }}" }
    - { limit_type: 'hard', limit_item: 'nproc', value: "{{ max_processes }}" }
  tags:
    - tuning

################################################################################
# Logging
################################################################################

- name: Configure rsyslog for centralized logging
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-operation-shadow.conf
    owner: root
    group: root
    mode: '0644'
  when: syslog_server is defined
  notify: restart rsyslog
  tags:
    - logging

################################################################################
# Cleanup
################################################################################

- name: Remove unnecessary packages
  apt:
    name:
      - telnet
      - rsh-client
      - rsh-redone-client
    state: absent
  tags:
    - security
    - cleanup

- name: Clean up package cache
  apt:
    autoclean: yes
    autoremove: yes
  tags:
    - cleanup

################################################################################
# Final Verification
################################################################################

- name: Verify common services are running
  service_facts:
  tags:
    - verify

- name: Display configured hostname
  debug:
    msg: "✓ {{ inventory_hostname }} configured with common role"
  tags:
    - verify


