---
# Ansible Hardening Playbook - Episode 20
# Hardening 50 servers automation

- name: Security Hardening - KERNEL SHADOWS
  hosts: all
  become: yes
  
  vars:
    hardening_level: "cis_level_2"
    enable_apparmor: true
    enable_auditd: true
  
  tasks:
    # 1. System Updates
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
    
    # 2. Install security tools
    - name: Install security packages
      apt:
        name:
          - aide
          - auditd
          - apparmor
          - apparmor-utils
          - ufw
          - fail2ban
        state: present
    
    # 3. Kernel hardening (sysctl)
    - name: Copy sysctl hardening config
      copy:
        src: ../sysctl.d/99-hardening.conf
        dest: /etc/sysctl.d/99-hardening.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload sysctl
    
    # 4. AppArmor profiles
    - name: Copy AppArmor profiles
      copy:
        src: ../apparmor/profiles/
        dest: /etc/apparmor.d/
        owner: root
        group: root
        mode: '0644'
      when: enable_apparmor
      notify: reload apparmor
    
    # 5. SSH hardening
    - name: Deploy hardened SSH config
      copy:
        src: ../service-configs/sshd_config.hardened
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
      notify: restart sshd
    
    # 6. Firewall
    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
    
    - name: Allow SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp
    
    # 7. Auditd rules
    - name: Copy auditd rules
      copy:
        src: ../audit.rules
        dest: /etc/audit/rules.d/hardening.rules
      when: enable_auditd
      notify: restart auditd
    
    # 8. Disable unused services
    - name: Disable unnecessary services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop:
        - avahi-daemon
        - cups
      ignore_errors: yes
  
  handlers:
    - name: reload sysctl
      command: sysctl -p /etc/sysctl.d/99-hardening.conf
    
    - name: reload apparmor
      command: apparmor_parser -r /etc/apparmor.d/*
    
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
    
    - name: restart auditd
      systemd:
        name: auditd
        state: restarted
