# EPISODE 25: Kubernetes Deployment - SOLUTION
# Season 7: Production & Advanced Topics

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-web
  namespace: shadow-ops
  labels:
    app: shadow-web
    component: frontend
    episode: "25"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shadow-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: shadow-web
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: NGINX_HOST
          value: "shadow.local"
        - name: NGINX_PORT
          value: "80"
        envFrom:
        - configMapRef:
            name: shadow-config
        - secretRef:
            name: shadow-secrets
            optional: true

