---
# KERNEL SHADOWS: Episode 16 — Ansible & Infrastructure as Code
# Global Variables (apply to ALL hosts)
# Amsterdam → Berlin (Day 31-32)

################################################################################
# Global Configuration
################################################################################

# Operation metadata
operation_name: operation-shadow
operation_version: "1.0.0"
environment: production
datacenter: tempelhof-amsterdam

# Timezone
timezone: Europe/Amsterdam

# DNS servers
dns_servers:
  - 1.1.1.1
  - 8.8.8.8

################################################################################
# User Management
################################################################################

# System users to create
system_users:
  - name: deploy
    uid: 2000
    groups:
      - sudo
      - docker
    shell: /bin/bash
    ssh_key: "{{ lookup('file', '~/.ssh/deploy_key.pub') }}"

  - name: monitor
    uid: 2001
    groups: []
    shell: /bin/bash

# Admin users
admin_users:
  - max
  - dmitry
  - viktor

################################################################################
# SSH Configuration
################################################################################

ssh_port: 22
ssh_password_authentication: no
ssh_permit_root_login: no
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300

################################################################################
# Security
################################################################################

# Firewall rules (UFW)
firewall_allowed_ports:
  - 22    # SSH
  - 80    # HTTP
  - 443   # HTTPS
  - 8080  # App

# Fail2ban
fail2ban_enabled: yes
fail2ban_maxretry: 5
fail2ban_bantime: 3600

# Automatic updates
unattended_upgrades_enabled: yes

################################################################################
# Monitoring
################################################################################

# Node exporter (Prometheus)
node_exporter_port: 9100
node_exporter_enabled: yes

# Log shipping
log_aggregation_server: "monitor-01.operation-shadow.net:5044"

################################################################################
# Packages (Common Software)
################################################################################

common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - vim
  - htop
  - net-tools
  - ufw
  - fail2ban
  - ntp
  - python3-pip

################################################################################
# NTP Configuration
################################################################################

ntp_servers:
  - 0.europe.pool.ntp.org
  - 1.europe.pool.ntp.org
  - 2.europe.pool.ntp.org

################################################################################
# Backup Configuration
################################################################################

backup_enabled: yes
backup_retention_days: 30
backup_destination: "s3://operation-shadow-backups"

################################################################################
# Logging
################################################################################

log_level: info
syslog_server: "monitor-01.operation-shadow.net"

################################################################################
# Klaus's Notes:
#
# "Variables defined here apply to ALL 50 servers.
#  For group-specific vars, see group_vars/production.yml
#  For host-specific vars, use host_vars/hostname.yml
#
#  Precedence (low to high):
#    all.yml < group_vars < host_vars < playbook vars < extra vars
#
#  Keep it DRY. Define once, use everywhere."
################################################################################


